site_name: YHX 的笔记本
repo_url: https://github.com/yanhexiong/yanhexiong.github.io
repo_name : YHX/Notebook
site_author: YHX
site_description : YHX的笔记本
copyright: Copyright &copy; 2023 YHX

extra_javascript:
  - javascripts/feedback.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - mdx_math
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  favicon: images/favicon.jpg
  icon:
    logo: material/notebook-multiple
  name: 'material'
  custom_dir: overrides
  language: 'zh'
  font:
    code: Open Sans
  palette:
    primary: 'deep purple'
    accent: 'cyan'
    
  features:
    - content.code.copy
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - header.autohide
    - navigation.footer
    - search.highlight
    - search.suggest
extra:
  generator: true
  social:
    - icon: fontawesome/brands/qq 
      link: https://qm.qq.com/cgi-bin/qm/qr?k=0oPef1lvW_knPM3zPLyu8iKiu6k8vH7W&noverify=0
    - icon: fontawesome/brands/weixin 
      link: https://u.wechat.com/ECfhgHwp3l_a1NWdkKtptnU
plugins:
  - glightbox

nav:
  - 'Minecraft' : 
    - '凯の梦想乡': 'mc1.12.1.md'